name: CI-CD Pipeline

on:
  push:
    branches: [ main, Joao ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/org/apache/maven/plugins/maven-surefire-plugin
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Run tests
        run: mvn -B test -Dtest="!NutriPlanApplicationTests"

      - name: Upload test reports artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: target/surefire-reports

  package:
    name: Package (Build)
    runs-on: ubuntu-latest
    # roda em paralelo com tests (nenhum depends-on)
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install system deps (if needed)
        run: |
          echo "No extra apt packages needed by default"
          # se quiser instalar algo: sudo apt-get update && sudo apt-get install -y <pkg>

      - name: Build package (skip tests so tests job can run in parallel)
        run: mvn -B -DskipTests package

      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: target/*.jar

  notify:
    name: Notify (email)
    runs-on: ubuntu-latest
    needs: [tests, package]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install python deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Download artifacts (optional)
        uses: actions/download-artifact@v4
        with:
          name: test-report
          path: artifacts/test-report

      - name: Run notification script
        env:
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          TESTS_STATUS: ${{ needs.tests.result }}
          BUILD_STATUS: ${{ needs.package.result }}
        run: |
          python send_email.py